version: "3"

networks:
  tabunet:
    driver: bridge

services:
  tabula-driver:
    container_name: tabula-driver
    image: kalairen/tabula-driver
    # shm_size: "2gb"
    ports:
      - "9888:9888"
    networks:
      - tabunet
    depends_on:
      - tabula
  tabula:
    container_name: tabula
    image: kalairen/tabula
    networks:
      - tabunet
